# Site settings
title: void *
url: "https://byung-u.github.io"
baseurl: ""
description: >
    A=A+B-(B=A)

# My information
email: byungwoo.jeun@gmail.com
author: Byungwoo Jeon
profile: Ƨ⅃OW AИᗡ ƧTƎAᗡY
twitter_username: byungwoo_jeun
github_username: byung-u
disqus_shortname: byungwoo

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: byungwoo
  shortname: byungwoo

google_analytics:
  ua: UA-41925802-2

blame: "https://github.com/byung-u/byung-u.github.io/blame/master/_wiki"
